name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Debug Path
        run: |
          ls -R  # Listet alle Dateien und Ordner rekursiv auf

      - name: Install and Build
        run: |
          npm install
          npm run build -- --configuration production

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/kudos_care_frontend
            sudo chown -R $USER:$USER /var/www/kudos_care_frontend
            rm -rf /var/www/kudos_care_frontend/*
            # Hinweis: Du musst die Dateien jetzt noch vom Runner auf den Server übertragen
            # Am besten nutzt du dafür den 'appleboy/scp-action' Schritt
